// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// ⚠️ 이 파일은 샘플 파일입니다.
// Firebase 설정을 위해 `flutterfire configure` 명령어를 실행하면
// 이 파일은 자동으로 실제 Firebase 프로젝트 정보로 덮어씌워집니다.
//
// 설정 후 동작 확인:
// 1. Android: google-services.json 파일이 android/app/ 디렉토리에 있는지 확인
// 2. iOS: GoogleService-Info.plist 파일이 ios/Runner/ 디렉토리에 있는지 확인
// 3. 앱을 실행하여 Firebase 초기화가 정상적으로 되는지 확인
//
// 자세한 내용은 FIREBASE_SETUP.md 파일을 참고하세요.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBmhdiguNcO9Kiz-MEUrt3_LT-P1rn8P4',
    appId: '1:363758710643:web:40bc6f3b9280a5ff4e1f06',
    messagingSenderId: '363758710643',
    projectId: 'chickentone-a0f5c',
    authDomain: 'chickentone-a0f5c.firebaseapp.com',
    storageBucket: 'chickentone-a0f5c.firebasestorage.app',
    measurementId: 'G-DH6CKQ3HKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqvMht4J_u_nOlTANEqIRekUclBjA6rm8',
    appId: '1:363758710643:android:32c4bb69e28ed8734e1f06',
    messagingSenderId: '363758710643',
    projectId: 'chickentone-a0f5c',
    storageBucket: 'chickentone-a0f5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGmmT-qi9Usy8ZJoZWZB3v_r2iZCivEl0',
    appId: '1:363758710643:ios:ccad7364c2a79fc84e1f06',
    messagingSenderId: '363758710643',
    projectId: 'chickentone-a0f5c',
    storageBucket: 'chickentone-a0f5c.firebasestorage.app',
    iosBundleId: 'com.example.blueberryTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'YOUR_MACOS_BUNDLE_ID',
  );

  // Windows는 Web 설정을 사용 (FlutterFire는 Windows 공식 미지원)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBmhdiguNcO9Kiz-MEUrt3_LT-P1rn8P4',
    appId: '1:363758710643:web:40bc6f3b9280a5ff4e1f06',
    messagingSenderId: '363758710643',
    projectId: 'chickentone-a0f5c',
    storageBucket: 'chickentone-a0f5c.firebasestorage.app',
    authDomain: 'chickentone-a0f5c.firebaseapp.com',
    measurementId: 'G-DH6CKQ3HKX',
  );
}